version: '3'

services:
    db:
        image: postgres:13
        restart: always
        container_name: social_media_db
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_DB: ${POSTGRES_NAME}
        ports:
            - "5432:5432"

        networks:
            - webnet

    django:
        container_name: social_media_backend
        build:
            context: .
            dockerfile: docker/Dockerfile-django
        depends_on:
            - db
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_DB: ${POSTGRES_NAME}
            PYTHONUNBUFFERED: 0
            PYTHONPYCACHEPREFIX: ../__pycache__

        ports:
            - "8000:8000"
        command:
                bash -c "
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
        networks:
            - webnet

networks:
    webnet:
